In [6]:
import pandas as pd

df = pd.read_csv("club_signups.csv")

df.head(10)

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Soccer,2026-09-15 13:39,N
1,S010,61-3846,AHMED ZAKI,ahmed.zaki@student.guc.edu.eg,Management,alexandria,Chess,15/09/2026 03:12,false
2,S008,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Music,2026-09-14 23:32,Y
3,S035,61-4844,MOHAMED ADEL,mohamed.adel@student.guc.edu.eg,Engineering and Materials Science,Cairo,Debating,2026-09-17 11:15,yes
4,S004,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Chess Club,2026-09-13 22:36,yes
5,S012,55-9245,ALI IBRAHIM,ali.ibrahim@student.guc.edu.eg,MET,cairo,Robotics,15/09/2026 03:42,N
6,S007,61-2495,ahmed adel,AHMED.ADEL@STUDENT.GUC.EDU.EG,Pharma,Alex,Robotics,2026-09-14 17:03,Y
7,S005,61-4733,OMAR ADEL,omar.adel@student.guc.edu.eg,EMS,cairo,football,2026-09-13 23:52,1
8,S020,55-9245,ali ibrahim,ali.ibrahim@student.guc.edu.eg,MET,CAIRO,Music,2026-09-15 23:07,false
9,S033,55-9245,ali ibrahim,ali.ibrahim@student.guc.edu.eg,met,Cairo,music,2026-09-16 09:07,1

In [3]:
print("Shape:", df.shape)

Shape: (39, 9)

In [4]:
df.dtypes

signup_id       str
student_id      str
full_name       str
email           str
faculty         str
city            str
club            str
signed_up_at    str
fee_paid        str
dtype: object

In [5]:
categorical_columns = [
    "full_name",
    "email",
    "faculty",
    "city",
    "club",
    "fee_paid"
]

for column in categorical_columns:
    print(f"\n===== {column} =====")
    print(df[column].value_counts(dropna=False))

===== full_name =====
full_name
Laila Mostafa         4
Hana Zaki             3
Ziad Saleh            3
Sara Zaki             3
Mohamed Adel          3
ali ibrahim           2
Ali Ibrahim           2
Karim Kamel           2
Youssef Fathy         2
AHMED ZAKI            1
  Mohamed  Adel       1
MOHAMED ADEL          1
ALI IBRAHIM           1
ahmed adel            1
OMAR ADEL             1
AHMED ADEL            1
  Omar  Adel          1
mohamed adel          1
Farida Ibrahim        1
Mariam Kamel          1
Salma Ibrahim         1
  Laila  Mostafa      1
  Farida  Ibrahim     1
laila mostafa         1
Name: count, dtype: int64

===== email =====
email
ali.ibrahim@student.guc.edu.eg       5
mohamed.adel@student.guc.edu.eg      4
laila.mostafa@student.guc.edu.eg     4
hana.zaki@student.guc.edu.eg         3
ziad.saleh@student.guc.edu.eg        3
sara.zaki@student.guc.edu.eg         3
omar.adel@student.guc.edu.eg         2
farida.ibrahim@student.guc.edu.eg    2
LAILA.MOSTAFA@STUDENT.GUC.EDU.EG     2
karim.kamel@student.guc.edu.eg       2
youssef.fathy@student.guc.edu.eg     2
ahmed.zaki@student.guc.edu.eg        1
AHMED.ADEL@STUDENT.GUC.EDU.EG        1
ahmed.adel@student.guc.edu.eg        1
mariam.kamel@student.guc.edu.eg      1
salma.ibrahim@student.guc.edu.eg     1
MOHAMED.ADEL@STUDENT.GUC.EDU.EG      1
 mohamed.adel@student.guc.edu.eg     1
Name: count, dtype: int64

===== faculty =====
faculty
Pharmacy                                  7
EMS                                       7
IET                                       5
Management                                4
Information Engineering and Technology    4
MET                                       3
iet                                       3
Engineering and Materials Science         1
Pharma                                    1
met                                       1
Media Engineering and Technology          1
pharmacy                                  1
ems                                       1
Name: count, dtype: int64

===== city =====
city
Cairo         13
Alexandria    11
Giza           4
Alex           4
cairo          2
giza           2
alexandria     1
CAIRO          1
El Giza        1
Name: count, dtype: int64

===== club =====
club
Robotics       8
Music          5
Chess          4
football       4
Debating       3
Chess Club     3
Football       3
Soccer         2
music          2
chess          2
debate club    1
Music          1
Debate         1
Name: count, dtype: int64

===== fee_paid =====
fee_paid
yes      7
1        7
false    6
Y        5
N        4
TRUE     4
Yes      4
0        1
no       1
Name: count, dtype: int64

In [7]:
for column in ["faculty", "city", "club"]:
    df[column] = df[column].str.strip().str.lower()

In [8]:
faculty_map = {
    "met": "MET",
    "iet": "IET",
    "ems": "EMS",
    "pharmacy": "Pharmacy",
    "management": "Management",
    "information engineering and technology": "IET",
    "engineering and materials science": "EMS",
    "pharma": "Pharmacy",
    "media engineering and technology": "MET"
}

df["faculty"] = df["faculty"].replace(faculty_map)

In [9]:
city_map = {
    "cairo": "Cairo",
    "giza": "Giza",
    "el giza": "Giza",
    "alexandria": "Alexandria",
    "alex": "Alexandria"
}

df["city"] = df["city"].replace(city_map)

In [10]:
club_map = {
    "robotics": "Robotics",
    "debate": "Debate",
    "debating": "Debate",
    "debate club": "Debate",
    "music": "Music",
    "football": "Football",
    "soccer": "Football",
    "chess": "Chess",
    "chess club": "Chess"
}

df["club"] = df["club"].replace(club_map)

In [11]:
assert set(df["faculty"].unique()) <= {
    "MET", "IET", "EMS", "Pharmacy", "Management"
}

assert set(df["city"].unique()) <= {
    "Cairo", "Giza", "Alexandria"
}

assert set(df["club"].unique()) <= {
    "Robotics", "Debate", "Music", "Football", "Chess"
}

In [12]:
df["full_name"] = (
    df["full_name"]
    .str.split()
    .str.join(" ")
    .str.title()
)

In [13]:
df["email"] = df["email"].str.strip().str.lower()

In [16]:
df[["full_name", "email"]].head(10)

       full_name                             email
0      Hana Zaki      hana.zaki@student.guc.edu.eg
1     Ahmed Zaki     ahmed.zaki@student.guc.edu.eg
2   Mohamed Adel   mohamed.adel@student.guc.edu.eg
3   Mohamed Adel   mohamed.adel@student.guc.edu.eg
4  Laila Mostafa  laila.mostafa@student.guc.edu.eg
5    Ali Ibrahim    ali.ibrahim@student.guc.edu.eg
6     Ahmed Adel     ahmed.adel@student.guc.edu.eg
7      Omar Adel      omar.adel@student.guc.edu.eg
8    Ali Ibrahim    ali.ibrahim@student.guc.edu.eg
9    Ali Ibrahim    ali.ibrahim@student.guc.edu.eg

In [17]:
fee_map = {
    "yes": True,
    "y": True,
    "true": True,
    "1": True,
    "no": False,
    "n": False,
    "false": False,
    "0": False
}

df["fee_paid"] = (
    df["fee_paid"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map(fee_map)
)

In [18]:
print(df["fee_paid"].value_counts())
print(df["fee_paid"].dtype)

fee_paid
True     27
False    12
Name: count, dtype: int64
bool

In [19]:
assert df["fee_paid"].dtype == bool

In [23]:
df["signed_up_at"] = pd.to_datetime(
    df["signed_up_at"],
    format="mixed",
    dayfirst=True
)

In [25]:
df["signed_up_at"].dtype

dtype('<M8[us]')

In [26]:
df.duplicated().sum()

np.int64(3)

In [27]:
df[df.duplicated(keep=False)]

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Football,2026-09-15 13:39:00,False
15,S022,61-8224,Sara Zaki,sara.zaki@student.guc.edu.eg,EMS,Giza,Music,2026-09-16 01:39:00,True
20,S023,58-1125,Ziad Saleh,ziad.saleh@student.guc.edu.eg,IET,Cairo,Chess,2026-09-16 09:29:00,False
24,S022,61-8224,Sara Zaki,sara.zaki@student.guc.edu.eg,EMS,Giza,Music,2026-09-16 01:39:00,True
33,S023,58-1125,Ziad Saleh,ziad.saleh@student.guc.edu.eg,IET,Cairo,Chess,2026-09-16 09:29:00,False
34,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Football,2026-09-15 13:39:00,False

In [28]:
df = df.drop_duplicates().copy()

In [29]:
print(df.shape)

(36, 9)

In [30]:
df.duplicated(subset=["student_id", "club"]).sum()

np.int64(4)

In [31]:
df = df.sort_values("signed_up_at")

In [32]:
df = df.drop_duplicates(
    subset=["student_id", "club"],
    keep="last"
).copy()

In [33]:
assert not df.duplicated(
    subset=["student_id", "club"]
).any()

In [34]:
df.to_csv("club_signups_clean.csv", index=False)

In [35]:
df.shape

(32, 9)